### ISSUE TITLE
修改权限后，不生效

### ISSUE THREAD

**Issue by LeoChen0715** [donjan-deng/hyperf-casbin#1]

**Comment by LeoChen0715** [comment]
需要hyperf重启，权限控制才能生效

**Comment by donjan-deng** [comment]
贴出相关代码，casbin配置，缓存配置，hyperf版本，最好重现一下

**Comment by hsluoyz** [comment]
@DDDecade0715 需要开启enforcer的autoSave功能

**Comment by LeoChen0715** [comment]
> @DDDecade0715 需要开启enforcer的autoSave功能

在哪里开启这个设置

**Comment by hsluoyz** [comment]
@DDDecade0715 我仔细看了下代码，这个仓库adapter用的：https://github.com/php-casbin/database-adapter 这个adapter是支持AutoSave的，AutoSave的解释可以看Casbin官网：https://casbin.org/docs/en/adapters#autosave 也就是说autoSave功能应该是默认开启的。

你是怎么修改权限的？贴一下完整代码

**Comment by DDDecade0715** [comment]
![Uploading image.png…]()

**Comment by DDDecade0715** [comment]
![image](https://user-images.githubusercontent.com/29270630/108941973-0ae44680-7691-11eb-879b-3ae7499558ec.png)

**Comment by LeoChen0715** [comment]
![image](https://user-images.githubusercontent.com/29270630/108942154-6c0c1a00-7691-11eb-8e8b-6cdc74230b76.png)

**Comment by LeoChen0715** [comment]
修改角色权限，从而改变管理员的权限

**Comment by hsluoyz** [comment]
@DDDecade0715 你看下调用了deletePermissionsForUser() 和 addPermissionForUser()后数据库里的casbin_rule表里的策略是不是改变了

**Comment by LeoChen0715** [comment]
![image](https://user-images.githubusercontent.com/29270630/108943816-7976d380-7694-11eb-871a-2a086d97944f.png)
![image](https://user-images.githubusercontent.com/29270630/108943867-93181b00-7694-11eb-8f1e-e010db625533.png)
是有改变的

**Comment by hsluoyz** [comment]
@DDDecade0715 那没问题啊，你所说的“不生效”是指检查权限的时候？贴出来检查权限的代码

**Comment by donjan-deng** [comment]
还未支持deletePermissionsForUser这个方法，要删除所有权限建议调用rule模型直接删除记录后调用refreshCache，
```
$rule->where('ptype', 'p')->where('v0', $this->getRoleKey($id))->delete();
$rule->refreshCache();
Enforcer::loadPolicy();
```

**Comment by hsluoyz** [comment]
@donjan-deng 可是他说 调用了deletePermissionsForUser()  以后DB变了，说明这个方法已经支持了？

**Comment by donjan-deng** [comment]
> @donjan-deng 可是他说 调用了deletePermissionsForUser() 以后DB变了，说明这个方法已经支持了？

只是增加了addPermissionForUser的权限，使用deletePermissionsForUser是无效的

**Comment by LeoChen0715** [comment]
我觉得鉴权是查缓存的，所以要重启hyperf项目才重新生成权限缓存

**Comment by donjan-deng** [comment]
> 我觉得鉴权是查缓存的，所以要重启hyperf项目才重新生成权限缓存

如果不是直接操作数据库，缓存是通过saved和deleted两个事件自动刷新的

**Comment by donjan-deng** [comment]
@DDDecade0715 升级3.0版本，已经支持deletePermissionsForUser、AddPolicies、RemovePolicies等API

**Comment by hsluoyz** [comment]
@DDDecade0715

**Comment by hsluoyz** [comment]
@DDDecade0715 @donjan-deng plz close this issue if resolved.
