### ISSUE TITLE
配置文件修改了matchers不生效

### ISSUE THREAD

**Issue by SongXIXIXI** [donjan-deng/hyperf-casbin#10]
`[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && (r.act == p.act || p.act == '*')`

加了p.act == '*'

不知道有没有其他注意事项，还是我姿势有问题

**Comment by hsluoyz** [comment]
@basakest

**Comment by donjan-deng** [comment]
删除runtime,重启Hyperf,测试语法用官方编辑器<https://casbin.org/zh-CN/editor>

**Comment by SongXIXIXI** [comment]
好的，我再试一下
