### ISSUE TITLE
composer update 后报错

### ISSUE THREAD

**Issue by etoup** [donjan-deng/hyperf-casbin#11]
在项目目录composer update后无法使用，报下列错误
PHP Fatal error:  Class Donjan\Casbin\Adapters\Mysql\DatabaseAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updateFilteredPolicies) in /Users/apple/work/etoup/hyperf-admin/service/vendor/donjan-deng/hyperf-casbin/src/Adapters/Mysql/DatabaseAdapter.php on line 25

Fatal error: Class Donjan\Casbin\Adapters\Mysql\DatabaseAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updateFilteredPolicies) in /Users/apple/work/etoup/hyperf-admin/service/vendor/donjan-deng/hyperf-casbin/src/Adapters/Mysql/DatabaseAdapter.php on line 25
[2021-08-31 21:16:00 *13099.2]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Class Donjan\Casbin\Adapters\Mysql\DatabaseAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updateFilteredPolicies) in /Users/apple/work/etoup/hyperf-admin/service/vendor/donjan-deng/hyperf-casbin/src/Adapters/Mysql/DatabaseAdapter.php on line 25
[2021-08-31 21:16:00 $13096.0]	WARNING	check_worker_exit_status: worker#2[pid=13099] abnormal exit, status=255, signal=0

service composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 32 updates, 0 removals
  - Upgrading casbin/casbin (v3.7.0 => v3.9.0)
  - Upgrading donjan-deng/hyperf-casbin (3.6.0 => 3.6.1)
  - Upgrading friendsofphp/php-cs-fixer (v3.0.2 => v3.1.0)
  - Upgrading graham-campbell/result-type (v1.0.1 => v1.0.2)
  - Upgrading hyperf/database (v2.2.0 => v2.2.5)
  - Upgrading hyperf/devtool (v2.2.0 => v2.2.5)
  - Upgrading hyperf/filesystem (v2.2.0 => v2.2.6)
  - Upgrading hyperf/ide-helper (v2.2.0 => v2.2.5)
  - Upgrading hyperf/translation (v2.2.0 => v2.2.5)
  - Upgrading hyperf/utils (v2.2.4 => v2.2.5)
  - Upgrading hyperf/validation (v2.2.0 => v2.2.6)
  - Upgrading hyperf/watcher (v2.2.2 => v2.2.6.1)
  - Upgrading illuminate/collections (v8.55.0 => v8.57.0)
  - Upgrading illuminate/contracts (v8.55.0 => v8.57.0)
  - Upgrading illuminate/hashing (v8.55.0 => v8.57.0)
  - Upgrading illuminate/macroable (v8.55.0 => v8.57.0)
  - Upgrading illuminate/support (v8.55.0 => v8.57.0)
  - Upgrading league/flysystem (2.2.1 => 2.2.3)
  - Upgrading nesbot/carbon (2.51.1 => 2.52.0)
  - Upgrading phpoption/phpoption (1.7.5 => 1.8.0)
  - Upgrading phpstan/phpstan (0.12.94 => 0.12.96)
  - Upgrading swoole/ide-helper (4.7.0 => 4.7.1)
  - Upgrading symfony/cache (v5.3.4 => v5.3.7)
  - Upgrading symfony/console (v5.3.6 => v5.3.7)
  - Upgrading symfony/event-dispatcher (v5.3.4 => v5.3.7)
  - Upgrading symfony/expression-language (v5.3.4 => v5.3.7)
  - Upgrading symfony/finder (v5.3.4 => v5.3.7)
  - Upgrading symfony/options-resolver (v5.3.4 => v5.3.7)
  - Locking symfony/polyfill-php81 (v1.23.0)
  - Upgrading symfony/process (v5.3.4 => v5.3.7)
  - Upgrading symfony/string (v5.3.3 => v5.3.7)
  - Upgrading symfony/translation (v5.3.4 => v5.3.7)
  - Upgrading symfony/var-exporter (v5.3.4 => v5.3.7)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 32 updates, 0 removals
  - Upgrading hyperf/utils (v2.2.4 => v2.2.5): Extracting archive
  - Upgrading phpoption/phpoption (1.7.5 => 1.8.0): Extracting archive
  - Upgrading graham-campbell/result-type (v1.0.1 => v1.0.2): Extracting archive
  - Upgrading symfony/finder (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/translation (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading nesbot/carbon (2.51.1 => 2.52.0): Extracting archive
  - Upgrading hyperf/database (v2.2.0 => v2.2.5): Extracting archive
  - Upgrading symfony/string (v5.3.3 => v5.3.7): Extracting archive
  - Upgrading symfony/console (v5.3.6 => v5.3.7): Extracting archive
  - Upgrading symfony/var-exporter (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/cache (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/expression-language (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading casbin/casbin (v3.7.0 => v3.9.0): Extracting archive
  - Upgrading donjan-deng/hyperf-casbin (3.6.0 => 3.6.1): Extracting archive
  - Upgrading hyperf/translation (v2.2.0 => v2.2.5): Extracting archive
  - Upgrading hyperf/validation (v2.2.0 => v2.2.6): Extracting archive
  - Upgrading symfony/process (v5.3.4 => v5.3.7): Extracting archive
  - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
  - Upgrading symfony/options-resolver (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/event-dispatcher (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading friendsofphp/php-cs-fixer (v3.0.2 => v3.1.0): Extracting archive
  - Upgrading hyperf/devtool (v2.2.0 => v2.2.5): Extracting archive
  - Upgrading league/flysystem (2.2.1 => 2.2.3): Extracting archive
  - Upgrading hyperf/filesystem (v2.2.0 => v2.2.6): Extracting archive
  - Upgrading hyperf/ide-helper (v2.2.0 => v2.2.5): Extracting archive
  - Upgrading hyperf/watcher (v2.2.2 => v2.2.6.1): Extracting archive
  - Upgrading illuminate/macroable (v8.55.0 => v8.57.0): Extracting archive
  - Upgrading illuminate/contracts (v8.55.0 => v8.57.0): Extracting archive
  - Upgrading illuminate/collections (v8.55.0 => v8.57.0): Extracting archive
  - Upgrading illuminate/support (v8.55.0 => v8.57.0): Extracting archive
  - Upgrading illuminate/hashing (v8.55.0 => v8.57.0): Extracting archive
  - Upgrading phpstan/phpstan (0.12.94 => 0.12.96): Extracting archive
  - Upgrading swoole/ide-helper (4.7.0 => 4.7.1): Extracting archive

**Comment by hsluoyz** [comment]
@basakest

**Comment by etoup** [comment]
Upgrading casbin/casbin (v3.7.0 => v3.9.0): Extracting archive 恢复到v3.7.0版本就不报错了

**Comment by basakest** [comment]
php-casbin 下的一个接口新加了一个抽象方法，其他实现这个接口的，这个扩展还没有实现。我等早上提个 pr 吧
