### ISSUE TITLE
权限更新问题

### ISSUE THREAD

**Issue by jhansin-zhang** [donjan-deng/hyperf-casbin#16]
首先执行addPermissionForUser ，再执行getPermissionsForUser 获取不到最新的权限，只有重启hyperf或者添加Enforcer::loadPolicy();才能获取最新的权限，这个请问是为什么呢

**Comment by hsluoyz** [comment]
@donjan-deng

**Comment by jhansin-zhang** [comment]
追踪代码，跟踪到casbin基础组件中的$this->item 和roles.php中的$this->roles 在hyperf框架下，赋值方式可能有问题，读取的是上一次的数据

**Comment by donjan-deng** [comment]
提供版本和相关代码，该功能是跑过测试的[RbacApiTest.php](https://github.com/donjan-deng/hyperf-casbin/blob/master/tests/RbacApiTest.php)

**Comment by jhansin-zhang** [comment]
donjan-deng/hyperf-casbin: "3.9.1",
casbin:v3.12.0
php: 8.0.8 开启jit opcache
hyperf:2.2

追踪到代码casbin/casbin/src/Rbac/Default/RoleManager/Roles.php的 &loadOrStore方法，
![image](https://user-images.githubusercontent.com/52953730/139612788-41f4621a-589a-4019-abc7-36b7e151ad2f.png)
发现更新权限后偶尔不刷新，时好时坏

代码：
![image](https://user-images.githubusercontent.com/52953730/139612832-7945a41c-1f91-4230-bfdc-2ab4cec1e671.png)

**Comment by donjan-deng** [comment]
如果你使用的是自带模型，严格执行Enforcer::addPermissionForUser(sub,obj, act)
注意
deletePermissionsForUser如果没有任何权限是没有返回的
addPermissionForUser如果添加已有权限也没有返回

**Comment by jhansin-zhang** [comment]
不是这两个没返回，而是添加完后执行getPermissionsForUser 获取的是上一次的数据，比如第一次更新权限为a,成功，第二次更新为b ，返回的是a， 第三次权限更新为c，返回的是b
