### ISSUE TITLE
Enforcer::addRoleForUser 报错

### ISSUE THREAD

**Issue by Tokimekis** [donjan-deng/hyperf-casbin#2]
报错内容如下：

[2021-03-14 17:40:25] hyperf.ERROR: Call to undefined method stdClass::buildRoleLinks() [] []
[2021-03-14 17:40:25] hyperf.ERROR: #0 /www/hyperf/vendor/casbin/casbin/src/Enforcer.php(507): Casbin\Model\Model->buildRoleLinks()
#1 /www/sublet-admin-api/vendor/casbin/casbin/src/ManagementApi.php(448): Casbin\Enforcer->buildRoleLinks()
#2 /www/sublet-admin-api/vendor/casbin/casbin/src/ManagementApi.php(412): Casbin\Enforcer->addNamedGroupingPolicy()
#3 /www/sublet-admin-api/vendor/casbin/casbin/src/RbacApi.php(68): Casbin\Enforcer->addGroupingPolicy()
#4 /www/sublet-admin-api/vendor/donjan-deng/hyperf-casbin/src/Enforcer.php(121): Casbin\Enforcer->addRoleForUser()
#5 /www/sublet-admin-api/runtime/container/proxy/App_Service_AuthService.proxy.php(79): Donjan\Casbin\Enforcer->__call()

**Comment by hsluoyz** [comment]
@basakest

**Comment by basakest** [comment]
Can you show me the code that caused this error?@Tokimekis

**Comment by Tokimekis** [comment]
> Can you show me the code that caused this error?@Tokimekis

```php
class AuthService
{
    /**
     * @Inject()
     * @var Enforcer
     */
    protected Enforcer $enforcer;
    /**
     * 添加指定用户于角色的关联
     *
     * @param int    $uid  用户uid
     * @param string $role 角色别名
     * @return mixed
     */
    public function addRoleForUser(int $uid, string $role)
    {
        return $this->enforcer->addRoleForUser($uid, $role);
    }
}

class UserService
{
    public function create()
    {
        Db::beginTransaction();
        try {
            // do some thing..
            $authService = make(AuthService::class);
            $authService->addRoleForUser($user->uid, $role->alias);
            Db::commit();
        } catch (\Throwable $e) {
            Db::rollBack();
            $this->logger->error($e->getMessage());
            $this->logger->error($e->getTraceAsString());
            throw new ServiceException(ErrorCode::USER_CREATE_FAIL);
        }
        return true;
    }
}
```

**Comment by basakest** [comment]
I am not familiar with this framework. So I installed this framework and used this method. But it didn't cause any errors. How did you call this method?
![image](https://user-images.githubusercontent.com/47746206/111070008-ae937a80-850a-11eb-8752-94186a4af0d5.png)
![image](https://user-images.githubusercontent.com/47746206/111070022-beab5a00-850a-11eb-8f26-4d12b0f596e8.png)

**Comment by hsluoyz** [comment]
@techoner

**Comment by Tokimekis** [comment]
> I am not familiar with this framework. So I installed this framework and used this method. But it didn't cause any errors. How did you call this method?
> ![image](https://user-images.githubusercontent.com/47746206/111070008-ae937a80-850a-11eb-8752-94186a4af0d5.png)
> ![image](https://user-images.githubusercontent.com/47746206/111070022-beab5a00-850a-11eb-8f26-4d12b0f596e8.png)

sorry, I can't describe in english

This error will only be reported when executed in a transaction

**Comment by donjan-deng** [comment]
@Tokimekis 我重现了一下，并没有报错,均为最新版本,记得删除runtime文件夹，建议不要用int类型，使用string
AuthService.php
```
<?php

declare(strict_types=1);

namespace App\Service;

use Donjan\Casbin\Enforcer;
use Hyperf\Di\Annotation\Inject;

class AuthService
{

    /**
     * @Inject()
     * @var Enforcer
     */
    protected Enforcer $enforcer;

    public function addRoleForUser(int $uid, string $role)
    {
        return $this->enforcer->addRoleForUser($uid, $role);
    }

}
```
UserService.php
```
<?php

declare(strict_types=1);

namespace App\Service;

use Hyperf\DbConnection\Db;

class UserService
{

    public function create()
    {
        Db::beginTransaction();
        try {
            $authService = make(AuthService::class);
            $authService->addRoleForUser(1, 'admin');
            Db::commit();
        } catch (\Throwable $e) {
            Db::rollBack();
            throw $e;
        }
        return true;
    }

}
```
IndexController.php
```
    public function casbin(UserService $userService)
    {
        $result = $userService->create();
    }
```
![111111111111](https://user-images.githubusercontent.com/8256490/111095954-7d9e5e80-8579-11eb-9dde-491737f47081.jpg)

**Comment by Tokimekis** [comment]
> @Tokimekis 我重现了一下，并没有报错,均为最新版本,记得删除runtime文件夹，建议不要用int类型，使用string
> AuthService.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\Service;
> 
> use Donjan\Casbin\Enforcer;
> use Hyperf\Di\Annotation\Inject;
> 
> class AuthService
> {
> 
>     /**
>      * @Inject()
>      * @var Enforcer
>      */
>     protected Enforcer $enforcer;
> 
>     public function addRoleForUser(int $uid, string $role)
>     {
>         return $this->enforcer->addRoleForUser($uid, $role);
>     }
> 
> }
> ```
> 
> UserService.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\Service;
> 
> use Hyperf\DbConnection\Db;
> 
> class UserService
> {
> 
>     public function create()
>     {
>         Db::beginTransaction();
>         try {
>             $authService = make(AuthService::class);
>             $authService->addRoleForUser(1, 'admin');
>             Db::commit();
>         } catch (\Throwable $e) {
>             Db::rollBack();
>             throw $e;
>         }
>         return true;
>     }
> 
> }
> ```
> 
> IndexController.php
> 
> ```
>     public function casbin(UserService $userService)
>     {
>         $result = $userService->create();
>     }
> ```
> 
> ![111111111111](https://user-images.githubusercontent.com/8256490/111095954-7d9e5e80-8579-11eb-9dde-491737f47081.jpg)

PHP版本7.4.13，基于hyperf官方容器运行，hyperf-casbin版本3.0，casbin版本3.1
根据报错信息，追踪到\Casbin\Model\Policy\buildRoleLinks() 方法，代码如下：
```php
    /**
     * Initializes the roles in RBAC.
     *
     * @param RoleManager $rm
     * @throws CasbinException
     */
    public function buildRoleLinks(RoleManager $rm): void
    {
        if (!isset($this->items['g'])) {
            return;
        }

        foreach ($this->items['g'] as $ast) {
            $ast->buildRoleLinks($rm);
        }
    }
```
打印其循环内的$ast，发现并非一个Assertion对象，而是一个stdClass对象，所以会报Call to undefined method stdClass::buildRoleLinks()

**Comment by donjan-deng** [comment]
@Tokimekis 禁用缓存功能，删除runtime，仍然报错就打包一份最小实现的代码出来

**Comment by Tokimekis** [comment]
> @Tokimekis 禁用缓存功能，删除runtime，仍然报错就打包一份最小实现的代码出来

解决了，应该是因为缓存问题，因为我中途修改了规则，但是程序运行使用的规则仍然是修改之前的规则，导致报错
