### ISSUE TITLE
分布式的情况下，修改策略后如何同步？

### ISSUE THREAD

**Issue by onekb** [donjan-deng/hyperf-casbin#20]
系统是用k8s分布式部署的
策略加载到内存后，如果其中一个容器更新了策略，该容器会刷新内存，那么其他容器还是旧的策略。
怎么解决这个问题？

**Comment by donjan-deng** [comment]
参考下官方，原项目改造的话需要提供一个Watcher，本项目目前还未包含Watcher，下一步计划先支持Redis Watcher
<https://casbin.org/docs/zh-CN/watchers>
<https://casbin.org/docs/zh-CN/k8s>

**Comment by onekb** [comment]
QAQ 哭死 刚写完watcher https://github.com/onekb/hyperf-casbin/tree/watcher-abandon 大佬的代码学习了 麻烦发个版本

**Comment by onekb** [comment]
是还需要配什么吗，config的watcher.enabled打开后还是不行。如果启动服务后没有使用Enforcer:: 就不会触发EnforcerFactory __invoke里的$enforcer->setWatcher了吧？

**Comment by donjan-deng** [comment]
你安装dev-master版本重新发布配置试试，我没有太多测试环境，所以还未正式发布。监听订阅是一个独立的子进程，Watcher只实现了更新策略发布消息。

**Comment by onekb** [comment]
我是通过clone项目后通过composer.json的repositories链过去的。测好了，可以更新缓存。刚才是我忘记把数据库里已经存在的权限删掉，重复addRoleForUser导致的不生效。
