### ISSUE TITLE
Hyperf 3.0 启动失败

### ISSUE THREAD

**Issue by a77uu** [donjan-deng/hyperf-casbin#31]
PHP Version: 8.0
Hyperf/framework Version: 3.0.0
使用热更新命令启动项目，提示：
`
Fatal error: Type of Donjan\Casbin\Process\CasbinProcess::$name must be string (as in class Hyperf\Process\AbstractProcess) in ~/myProject/vendor/donjan-deng/hyperf-casbin/src/Process/CasbinProcess.php on line 12
`

**Comment by hsluoyz** [comment]
@donjan-deng
