### ISSUE TITLE
CasbinProcess的成员变量$name缺少string类型声明

### ISSUE THREAD

**Issue by Tokimekis** [donjan-deng/hyperf-casbin#32]
donjan-deng/hyperf-casbin/src/Process/CasbinProcess.php on line 12

`
public $name = 'casbin-watcher';
`

应修改为
`
public string $name = 'casbin-watcher';
`

**Comment by hsluoyz** [comment]
@donjan-deng

**Comment by donjan-deng** [comment]
#31
