### ISSUE TITLE
性能改进建议

### ISSUE THREAD

**Issue by imlida** [donjan-deng/hyperf-casbin#4]
打印sql日志发现每次判断权限都需要查询全表，如果表数据很大这样查询效率非常低吧
![image](https://user-images.githubusercontent.com/5794390/112279728-31f95c80-8cbf-11eb-869c-412248e8e61a.png)

**Comment by hsluoyz** [comment]
@imlida 不调用数据库的话还好吧，Casbin可以在内存中查询策略

**Comment by imlida** [comment]
那只能把单独建一张表来存储用户角色，这里只做角色授权了，如果授权角色也存在这张表的话有几万个用户那这张表就会有几万条记录，没办法查询了。

**Comment by donjan-deng** [comment]
规则常驻内存，并不是每次判断都会查询数据库，前提是未重启Hyperf、未修改规则
