### ISSUE TITLE
3.23.2版本不存在config方法

### ISSUE THREAD

**Issue by ren-jimmy** [donjan-deng/hyperf-casbin#40]
![image](https://github.com/user-attachments/assets/55d4dd7d-4e93-4931-9d69-56d4c836dfdd)
<img width="715" alt="image" src="https://github.com/user-attachments/assets/2354ab33-d12e-4dce-a5de-425189896b12">

**Comment by ren-jimmy** [comment]
好像要 composer require hyperf/support 和 composer require hyperf/config   

要强依赖
![image](https://github.com/user-attachments/assets/91a7c354-5ce8-4ad5-ada0-d95c2b3b53ba)

**Comment by hsluoyz** [comment]
@donjan-deng

**Comment by zhaohao19941221** [comment]
也是醉了
