### ISSUE TITLE
采坑了：Enforcer 不能持久容器化，因为对应的数据也被持久化了

### ISSUE THREAD

**Issue by laojiu** [donjan-deng/hyperf-casbin#5]
Enforcer 不能持久容器化，因为对应的数据也被持久化了，导致数据无法实时对权限数据更新
    
vendor/donjan-deng/hyperf-casbin/src/Enforcer.php
`
   public static function __callStatic($method, $parameters)
    {
        return ApplicationContext::getContainer()->get(Enforcer::class)->{$method}(...$parameters);
    }
`

想了下解决办法有好几种方式：
第一种是把这个容器注入的方式改成make（类似new操作，但是依赖会继续注入）
第二种就是我PR的方式直接不给成员变量赋值，每次都会重新获取，如果觉得每次查询很麻烦，可以开启缓存，实际也是读取的实时的缓存数据
第三种就是在模型操作事件中 再调用一个处理清除clean的方法（目前只是清除了缓存的key）---- 这种方式只适合单机应用

**Comment by hsluoyz** [comment]
@laojiu can you make a PR to fix it?

**Comment by laojiu** [comment]
ok  已经提交 这个问题主要是长生命周期成员属性变量赋值的问题

**Comment by hsluoyz** [comment]
PR: https://github.com/donjan-deng/hyperf-casbin/pull/6

**Comment by donjan-deng** [comment]
@laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by laojiu** [comment]
> @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？

单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；

**Comment by laojiu** [comment]
> @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？

单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；

**Comment by donjan-deng** [comment]
> > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> 
> 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；

参见<https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16>addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model

**Comment by laojiu** [comment]
> > > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> > 
> > 
> > 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；
> 
> 参见https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model

我刚看了源码 确实是会更新model；我上次在本地就是类似集群操作的，我当时误以为model没有更新，那我上面的结论还有待验证，我明天继续调试测试下，多谢了；如果是集群这个model的更新是不是就会有问题呢？

**Comment by laojiu** [comment]
> > > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> > 
> > 
> > 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；
> 
> 参见https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model

我刚看了源码 确实是会更新model；我上次在本地就是类似集群操作的，我当时误以为model没有更新，那我上面的结论还有待验证，我明天继续调试测试下，多谢了；如果是集群这个model的更新是不是就会有问题呢？

**Comment by donjan-deng** [comment]
> > > > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> > > 
> > > 
> > > 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；
> > 
> > 
> > 参见[https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model](https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal%E6%96%B9%E6%B3%95%EF%BC%8C%E8%B0%83%E7%94%A8API%E6%9B%B4%E6%94%B9%E6%9D%83%E9%99%90%E6%97%B6%EF%BC%8C%E9%83%BD%E6%98%AF%E5%85%88%E8%B0%83%E7%94%A8adapter%E6%93%8D%E4%BD%9C%E6%95%B0%E6%8D%AE%E5%BA%93%EF%BC%8C%E5%90%8E%E7%9B%B4%E6%8E%A5%E6%9B%B4%E6%96%B0model)
> 
> 我刚看了源码 确实是会更新model；我上次在本地就是类似集群操作的，我当时误以为model没有更新，那我上面的结论还有待验证，我明天继续调试测试下，多谢了；如果是集群这个model的更新是不是就会有问题呢？

针对多实例是通过单独的watcher实现的，目前还没有PHP版本的watcher，你可以在应用级事件执行Enforcer::loadPolicy(); 重新加载策略

**Comment by donjan-deng** [comment]
> > > > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> > > 
> > > 
> > > 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；
> > 
> > 
> > 参见[https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model](https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal%E6%96%B9%E6%B3%95%EF%BC%8C%E8%B0%83%E7%94%A8API%E6%9B%B4%E6%94%B9%E6%9D%83%E9%99%90%E6%97%B6%EF%BC%8C%E9%83%BD%E6%98%AF%E5%85%88%E8%B0%83%E7%94%A8adapter%E6%93%8D%E4%BD%9C%E6%95%B0%E6%8D%AE%E5%BA%93%EF%BC%8C%E5%90%8E%E7%9B%B4%E6%8E%A5%E6%9B%B4%E6%96%B0model)
> 
> 我刚看了源码 确实是会更新model；我上次在本地就是类似集群操作的，我当时误以为model没有更新，那我上面的结论还有待验证，我明天继续调试测试下，多谢了；如果是集群这个model的更新是不是就会有问题呢？

针对多实例是通过单独的watcher实现的，目前还没有PHP版本的watcher，你可以在应用级事件执行Enforcer::loadPolicy(); 重新加载策略

**Comment by liminworks** [comment]
你可以在应用级事件执行Enforcer::loadPolicy(); 重新加载策略？是在每次调用Enforcer::enforce()前，调用Enforcer::loadPolicy()方法吗？

**Comment by liminworks** [comment]
你可以在应用级事件执行Enforcer::loadPolicy(); 重新加载策略？是在每次调用Enforcer::enforce()前，调用Enforcer::loadPolicy()方法吗？

**Comment by liminworks** [comment]
> > > > @laojiu 单个实例应该不会出现这种问题，集群环境中，多个实例间权限数据不同步？
> > > 
> > > 
> > > 单应用也会有问题，不会更新数据 $this->guards[$name]下的model， 这个对象不会随着cache的变更重新获取，因为他已经被放进了长生命周期里面了；咱们虽在在模型更新或者保存时已经清理了cache，但是修改不到$this->guards[$name]；可以尝试通过debug工具就看到了；
> > 
> > 
> > 参见[https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal方法，调用API更改权限时，都是先调用adapter操作数据库，后直接更新model](https://github.com/php-casbin/php-casbin/blob/44028c74dba3a8fbff8f51436692e7969ce488d4/src/InternalEnforcer.php#L16addPolicyInternal%E6%96%B9%E6%B3%95%EF%BC%8C%E8%B0%83%E7%94%A8API%E6%9B%B4%E6%94%B9%E6%9D%83%E9%99%90%E6%97%B6%EF%BC%8C%E9%83%BD%E6%98%AF%E5%85%88%E8%B0%83%E7%94%A8adapter%E6%93%8D%E4%BD%9C%E6%95%B0%E6%8D%AE%E5%BA%93%EF%BC%8C%E5%90%8E%E7%9B%B4%E6%8E%A5%E6%9B%B4%E6%96%B0model)
> 
> 我刚看了源码 确实是会更新model；我上次在本地就是类似集群操作的，我当时误以为model没有更新，那我上面的结论还有待验证，我明天继续调试测试下，多谢了；如果是集群这个model的更新是不是就会有问题呢？

你可以在应用级事件执行Enforcer::loadPolicy(); 重新加载策略？是在每次调用Enforcer::enforce()前，调用Enforcer::loadPolicy()方法吗？
