### ISSUE TITLE
3.1版本有bug，，少了一个实现接口的方法，导致3.1无法使用

### ISSUE THREAD

**Issue by liminworks** [donjan-deng/hyperf-casbin#9]
![C5C535B0-1A9D-4eb6-B989-0A236C0897DB](https://user-images.githubusercontent.com/16682560/129681228-d49044bc-6cf8-48f8-895b-c37277808cf3.png)
![F18D73E8-EE00-4d1d-AF4D-A71ABDC08767](https://user-images.githubusercontent.com/16682560/129681235-8936a73f-fa85-415f-8dff-38ca9bd227a5.png)
DatabaseAdapter::updatePolicies() 方法

**Comment by hsluoyz** [comment]
@basakest

**Comment by basakest** [comment]
我刚才看了一下，3.6 版本中已经有人添加这个方法了，更新一下应该就可以了
